services:
  frontend:
    container_name: frontend
    build:
      context: ./rb-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./rb-frontend:/app
      - node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://backend:8000/api
    networks:
      - app-network

  backend:
    container_name: backend
    build: 
      context: ./rb-backend/rentalBooking
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1 
      - PYTHONBREAKPOINT=ipdb.set_trace
    volumes:
      - ./rb-backend/rentalBooking:/app
      - /app/rentalBooking/__pycache__
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    container_name: db
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=rentalbookingdb
      - POSTGRES_USER=rbusr
      - POSTGRES_PASSWORD=fdBM&uVz*9;c5TR2Kt@
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rbusr -d rentalbookingdb"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network

volumes:
  postgres_data:
  node_modules:

networks:
  app-network:
    driver: bridge