# Generated by Django 5.1.6 on 2025-02-19 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='description',
            field=models.TextField(blank=True, db_index=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='location',
            field=models.CharField(db_index=True, max_length=255, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='price',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10, verbose_name='price per night'),
        ),
        migrations.AlterField(
            model_name='rental',
            name='title',
            field=models.CharField(db_index=True, max_length=100, verbose_name='title'),
        ),
    ]
