# Generated by Django 5.1.6 on 2025-02-22 19:08

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_rental_description_alter_rental_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('real_estate', 'Real Estate'), ('vehicles', 'Vehicles'), ('equipment', 'Equipment'), ('life_style', 'Life & Style')], db_index=True, default='real_estate', max_length=100, verbose_name='name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.AddField(
            model_name='rental',
            name='category',
            field=models.ForeignKey(default=api.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='api.category'),
        ),
    ]
